### ISSUE TITLE
[BUG] The bot refuses to work

### ISSUE THREAD

**Issue by moseechev** [Exiled-Team/DiscordIntegration#104]
**Describe the bug**
Bot doesn't work

**To Reproduce**
1. Start the bot

**Expected behavior**
To see the bot working

**Server logs**
```
2022-06-13 22:34:54.185 +03:00 | Internal            | Logger         | Started logging. Game version: 11.2.0, private beta: NO.
2022-06-13 22:36:05.377 +03:00 | Remote Admin        | Administrative | SERVER CONSOLE performed a soft server restart.
```
lmao idk what do you mean by MA_log and SCP_log i've searched but i couldn't find it

**EXILED Version ("latest" is not a version):**
5.2.1

**Results of show plugins command in console:**

```
ScpSwap:
        - Author: Originally written by Cyanox, modifications by KoukoCocoa & Thomasjosif
        - Version: 1.3.2
        - Required Exiled Version: 2.1.29.0
        - Prefix: scp_swap
        - Priority: Medium
RemoteKeycard:
        - Author: Beryl (Maintained by Parkeymon)
        - Version: 3.1.3
        - Required Exiled Version: 5.2.0
        - Prefix: remotekeycard
        - Priority: Medium
DiscordIntegration:
        - Author: Exiled Team
        - Version: 6.0.2.0
        - Required Exiled Version: 5.2.0
        - Prefix: discord_integration
        - Priority: Medium
Exiled.CustomRoles:
        - Disabled
        - Author: Exiled Team
        - Version: 5.2.1.0
        - Required Exiled Version: 5.2.1.0
        - Prefix: exiled_custom_roles
        - Priority: Medium
Exiled.Updater:
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 5.2.1.0
        - Prefix: exiled_updater
        - Priority: Medium
Stalky106:
        - Author: RogerFK && Raul125
        - Version: 3.3.2
        - Required Exiled Version: 5.0.0
        - Prefix: ST106
        - Priority: Medium
```

**Additional context**

The bot doesn't update its status, although it appears as online:
https://imgur.com/a/k61HKeh

This is what it looks like when you commit ./DiscordIntegratio.Bot:

```
$ ./DiscordIntegration.Bot
22:25:50 [1] Init    Setting up commands...
22:25:50 [1] Init    Setting up logging..
22:25:50 [1] Init    Registering commands..
22:25:50 [1] Init    Logging in..
22:25:50 Discord     Discord.Net v3.5.0 (API v9)
22:25:50 [1] Init    Login successful.
22:25:50 Gateway     Connecting
22:25:52 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
22:25:52 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
22:25:52 Gateway     Connected
22:25:52 Gateway     A Ready handler has thrown an unhandled exception.:
Discord.Net.HttpException: The server responded with error 50001: Missing Access
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 guildId, CreateApplicationCommandParams[] commands, RequestOptions options)
   at Discord.Rest.InteractionHelper.BulkOverwriteGuildCommandsAsync(BaseDiscordClient client, UInt64 guildId, ApplicationCommandProperties[] args, RequestOptions options)
   at Discord.Rest.ClientHelper.BulkOverwriteGuildApplicationCommandAsync(BaseDiscordClient client, UInt64 guildId, ApplicationCommandProperties[] properties, RequestOptions options)
   at Discord.Interactions.InteractionService.RegisterCommandsToGuildAsync(UInt64 guildId, Boolean deleteMissing)
   at DiscordIntegration.Bot.Bot.<Init>b__26_0()
   at Discord.EventExtensions.InvokeAsync(AsyncEvent1 eventHandler)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func1 action)
22:25:52 Gateway     Ready
```

This is what it looks like in game configs:

```
discord_integration:
# Indicates whether the plugin is enabled or not
  is_enabled: true
  # Bot-related configs
  bot:
  # Bot IP address
    i_p_address: 127.0.0.1
    # Bot port
    port: 9000
    # Bot status update interval, in seconds
    status_update_interval: 5
    # Channel topic update interval, in seconds
    channel_topic_update_interval: 300
    # Time to wait before trying to reconnect again, in seconds
    reconnection_interval: 5
  # Indicates events that should be logged or not
  events_to_log:
    sending_remote_admin_commands: true
    sending_console_commands: true
    round_started: true
    round_ended: true
    waiting_for_players: true
    reporting_cheater: true
    hurting_player: true
    player_dying: true
    player_throwing_grenade: true
    player_used_medical_item: true
    player_entering_pocket_dimension: true
    player_escaping_pocket_dimension: true
    player_item_dropped: false
    player_pickingup_item: false
    player_intercom_speaking: true
    player_joined: true
    player_interacting_door: false
    player_removing_handcuffs: true
    player_activating_warhead_panel: true
    player_interacting_elevator: true
    player_interacting_locker: true
    player_triggering_tesla: true
    player_closing_generator: true
    player_opening_generator: true
    player_inserting_generator_tablet: true
    player_ejecting_generator_tablet: true
    player_unlocking_generator: true
    player_left: true
    player_banned: true
    reloading_player_weapon: false
    changing_player_role: true
    respawning_team: true
    handcuffing_player: true
    changing_player_item: false
    changing_player_group: true
    upgrading_scp914_items: true
    activating_scp914: true
    changing_scp914_knob_setting: true
    decontaminating: true
    stopping_warhead: true
    starting_warhead: true
    warhead_detonated: true
    generator_activated: true
    scp106_teleporting: true
    containing_scp106: true
    creating_scp106_portal: true
    gaining_scp079_experience: true
    scp079_interacting_tesla: true
    gaining_scp079_level: true
  # Indicates events that should be logged to the staff-only channel. These logs always ignore DNT, and will always show the player's UserID.
  staff_only_events_to_log:
    sending_remote_admin_commands: true
    sending_console_commands: true
    round_started: true
    round_ended: true
    waiting_for_players: true
    reporting_cheater: true
    hurting_player: true
    player_dying: true
    player_throwing_grenade: true
    player_used_medical_item: true
    player_entering_pocket_dimension: true
    player_escaping_pocket_dimension: true
    player_item_dropped: false
    player_pickingup_item: false
    player_intercom_speaking: true
    player_joined: true
    player_interacting_door: false
    player_removing_handcuffs: true
    player_activating_warhead_panel: true
    player_interacting_elevator: true
    player_interacting_locker: true
    player_triggering_tesla: true
    player_closing_generator: true
    player_opening_generator: true
    player_inserting_generator_tablet: true
    player_ejecting_generator_tablet: true
    player_unlocking_generator: true
    player_left: true
    player_banned: true
    reloading_player_weapon: false
    changing_player_role: true
    respawning_team: true
    handcuffing_player: true
    changing_player_item: false
    changing_player_group: true
    upgrading_scp914_items: true
    activating_scp914: true
    changing_scp914_knob_setting: true
    decontaminating: true
    stopping_warhead: true
    starting_warhead: true
    warhead_detonated: true
    generator_activated: true
    scp106_teleporting: true
    containing_scp106: true
    creating_scp106_portal: true
    gaining_scp079_experience: true
    scp079_interacting_tesla: true
    gaining_scp079_level: true
  # Indicates whether players' IP Addresses should be logged or not
  should_log_i_p_addresses: true
  # Indicates whether players' user ids should be logged or not
  should_log_user_ids: true
  # Indicates whether server errors should be logged or not.
  log_errors: true
  # Indicates whether players' with the "Do not track" enabled, should be logged or not
  should_respect_do_not_track: false
  # Indicates whether only friendly fire for damage should be logged or not
  should_log_friendly_fire_damage_only: false
  # Indicates whether only friendly fire for kills should be logged or not
  should_log_friendly_fire_kills_only: false
  # Indicates what damage types aren't allowed to be logged for hurting events. These filters will not apply to death logs.
  blacklisted_damage_types:
  - Scp207
  - PocketDimension
  # Indicates whether or not only player-dealt damage should be logged in hurting events.
  only_log_player_damage: false
  # The date format that will be used throughout the plugin (es. dd/MM/yy HH:mm:ss or MM/dd/yy HH:mm:ss)
  date_format: dd/MM/yy HH:mm:ss
  # Indicates whether the debug is enabled or not
  is_debug_enabled: true
  # The list of trusted admins, whos command usage will not be logged.
  trusted_admins: []
  # The plugin language
  language: english
```

This is what DiscordIntegration.Bot-config.json looks like:

```
{
  "BotTokens": {
    "1": "REDACTED"
  },
  "Channels": {
    "1": {
      "Logs": {
        "Commands": [
          985673356458229800
        ],
        "GameEvents": [
          985673356458229800
        ],
        "Bans": [
          985673356458229800
        ],
        "Reports": [
          985673356458229800
        ],
        "StaffCopy": [
          985673356458229800
        ],
        "Errors": [
          985673356458229800
        ]
      },
      "TopicInfo": [
        985673356458229800
      ],
      "CommandChannel": [
        985673356458229800
      ]
    }
  },
  "ValidCommands": {
    "1": {
      "0": [
        "di"
      ]
    }
  },
  "DiscordServerIds": {
    "1": 880254827832156181
  },
  "TcpServers": {
    "1": {
      "Port": 9000,
      "IpAddress": "127.0.0.1"
    }
  },
  "KeepAliveInterval": 2000,
  "MessageDelay": 1000,
  "Debug": true
}
```

This is what it looks like in game console:

```
[22:51:41] [INFO] [DiscordIntegration] [NET] Successfully connected to 127.0.0.1:9000.
[22:51:41] [DEBUG] [DiscordIntegration] Sent {"$type":"DiscordIntegration.Dependency.RemoteCommand, DiscordIntegration.Dependency","action":2,"parameters":["0/0"]} (119 bytes) to server.
[22:51:47] Waiting for players...
[22:51:47] [DEBUG] [DiscordIntegration] Sent {"$type":"DiscordIntegration.Dependency.RemoteCommand, DiscordIntegration.Dependency","action":2,"parameters":["0/30"]} (120 bytes) to server.
```

The bot's status, however, is still unaffected.

This is what scopes look like:
https://imgur.com/a/tG3tygs

Please help. I've tried pretty much everything.
