### ISSUE TITLE
[BUG] RNR command via DI does not work

### ISSUE THREAD

**Issue by SrLicht** [Exiled-Team/DiscordIntegration#61]
**Describe the bug**
When executing the RNR(restartnextround) command from discord nothing happens, there is no response from the server but the bot logs say that it was executed.

**To Reproduce**

Just use the command.

**Server logs**
![image](https://user-images.githubusercontent.com/36207738/132107998-d32a4e82-ef3c-495b-ae5f-bee118adb85e.png)
```cmd

[4/9/2021 5:59:55 p. m.] Server Console has run the command players.
[4/9/2021 6:03:47 p. m.] Server Console has run the command rnr.
[4/9/2021 6:03:50 p. m.] Server Console has run the command restartnextround.
```
[7777-RAlog.txt](https://github.com/Exiled-Team/DiscordIntegration/files/7110521/7777-RAlog.txt)
**Bot Logs**
```cmd
[DISCORD][DEBUG] SrLicht#9292 (230179802340917248) executed a command: [rnr]
[DISCORD][DEBUG] "[17:52:06] :keyboard: SrLicht#9292 (230179802340917248@discord) [None] used command: rnr" message has been sent in "🧰「comandos-cerb-3」" (735224742461571072).
[DISCORD][DEBUG] SrLicht#9292 (230179802340917248) executed a command: [restartnextround]
[DISCORD][DEBUG] Bot activity has been set to "0/45".
[DISCORD][DEBUG] "[17:52:09] :keyboard: SrLicht#9292 (230179802340917248@discord) [None] used command: restartnextround" message has been sent in "🧰「comandos-cerb-3」" (735224742461571072)

```
![image](https://user-images.githubusercontent.com/36207738/132107850-d3073aca-666f-4fc1-a887-d01f73b62d7e.png)

**EXILED Version ("latest" is not a version):**
Version 3.0.0-alpha.80

**Results of `show plugins` command in console:**
```yml
[2021-09-04 18:00:51.822 -03:00] Total number of plugins: 10
Enabled plugins: 9
Disabled plugins: 1

Exiled.Events:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_events
        - Priority: Highest
CerberusTweaks:
        - Author: Cerberus Team: Uriel, Licht, Beryl
        - Version: 3.0.5
        - Required Exiled Version: 3.0.0
        - Prefix: cerberus_tweaks
        - Priority: Medium
DiscordIntegration:
        - Author: Exiled Team
        - Version: 4.0.4.0
        - Required Exiled Version: 3.0.0
        - Prefix: discord_integration
        - Priority: Medium
Exiled.Permissions:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_permissions
        - Priority: Medium
StaffLogs:
        - Author: Cerberus Team: Uriel, Licht y Andrés
        - Version: 1.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: staff_logs
        - Priority: Medium
Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_custom_items
        - Priority: Medium
Better-SCP-079:
        - Author: SrLicht
        - Version: 1.0.3
        - Required Exiled Version: 3.0.0.0
        - Prefix: better079
        - Priority: Medium
CerberusGamemodes:
        - Author: Cerberus Team: Uriel, Licht, Beryl
        - Version: 1.5.1
        - Required Exiled Version: 3.0.0.0
        - Prefix: cerberusgamemodes
        - Priority: Medium
Exiled.CreditTags:
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_credits
        - Priority: Medium
Exiled.Updater:
        - Disabled
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_updater
        - Priority: Medium
```

**Additional context**
Although the command is executed and in the logs of the RA command it comes out, apparently it does not work because I have to manually run RNR from the server console to use it.
